---
branches:
  only:
    - master

jobs:
  include:
    - name: "run make check on stratis-docs"
      env: TASK=check

    # VERIFICATION OF TEST INFRASTRUCTURE
    - name: "run yamllint 1.23.0 on .travis.yml"
      language: python
      python: "3.7.6"
      install: pip3 install yamllint==1.23.0
      env: TASK=yamllint

script: make -f Makefile $TASK
