---
name: stratis-docs CI

# yamllint disable-line rule:truthy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checks:
    strategy:
      matrix:
        include:
          - dependencies: lyx zola
            task: make -f Makefile check
          - dependencies: yamllint
            task: make -f Makefile yamllint
    runs-on: ubuntu-18.04
    container: fedora:33
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: >
          dnf install -y
          make
          python-unversioned-command
          ${{ matrix.dependencies }}
      - name: Run test
        run: ${{ matrix.task }}
