---
name: stratis-docs CI

# yamllint disable-line rule:truthy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  docs-checks:
    runs-on: ubuntu-latest
    container: fedora:38  # CURRENT DEVELOPMENT ENVIRONMENT
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: dnf install -y make git gcc g++ lyx 'dnf-command(copr)'
      - name: Enable copr repo
        run: dnf copr enable atim/zola --assumeyes
      - name: Install zola
        run: dnf install zola --assumeyes
      - name: Run test
        run: make -f Makefile check

  ci-checks:
    runs-on: ubuntu-latest
    container: fedora:38  # CURRENT DEVELOPMENT ENVIRONMENT
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: dnf install -y make yamllint
      - name: Run test
        run: make -f Makefile yamllint
