---
name: stratis-docs weekly

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: 20 0 * * 0

  workflow_dispatch:

jobs:
  next-fedora-docs-checks:
    runs-on: ubuntu-latest
    container: fedora:39  # NEXT DEVELOPMENT ENVIRONMENT
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: dnf install -y make lyx 'dnf-command(copr)'
      - name: Enable copr repo
        run: dnf copr enable atim/zola --assumeyes
      - name: Install zola
        run: dnf install zola --assumeyes
      - name: Run test
        run: make -f Makefile check

  next-fedora-ci-checks:
    runs-on: ubuntu-latest
    container: fedora:39  # NEXT DEVELOPMENT ENVIRONMENT
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: dnf install -y make yamllint
      - name: Run test
        run: make -f Makefile yamllint
